name: vida_app
description: "A new Flutter project."

# Versão do app (major.minor.patch+build)
version: 1.0.0+4

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3   
  xml: ^6.5.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4



                    

  flutter_svg: ^2.0.9

  # Biblioteca para pegar informações do app (nome, versão, etc.)
  package_info_plus: ^8.0.0

  # Ícones padrão do iOS (usados em Flutter)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Regras de boas práticas de código
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/models/female/
    - assets/models/male/