// ============================================================================
// FILE: lib/core/onboarding/questions.dart
//
// Define a estrutura das perguntas iniciais do app.
// - Mantém o fluxo em 2 etapas (personal + life) para não quebrar o gate atual
// - Adiciona uma tela inicial explicativa
// - Organiza as perguntas por setores da vida com títulos claros
// - Mantém ids importantes já usados no app, como nickname, gender, dob, cpf,
//   focus e goal
// ============================================================================

enum QuestionType { info, options, text, date }

enum OnboardingStage { personal, life }

class Question {
  final String id;
  final String question;
  final QuestionType type;
  final List<String> options;
  final bool optional;
  final String? helper;
  final String? sectionTitle;
  final String? sectionDescription;
  final String? ctaText;

  const Question({
    required this.id,
    required this.question,
    required this.type,
    this.options = const [],
    this.optional = false,
    this.helper,
    this.sectionTitle,
    this.sectionDescription,
    this.ctaText,
  });
}

/// Etapa 1: base pessoal do usuário
final List<Question> personalQuestions = [
  const Question(
    id: 'intro_initial_context',
    type: QuestionType.info,
    question: 'Vamos personalizar seu app',
    helper:
        'Estas perguntas ajudam o app a entender sua realidade atual.\n\n'
        'Cada pessoa vive uma rotina diferente, então o app precisa conhecer '
        'seu contexto para avaliar suas áreas de forma mais justa.\n\n'
        'Responda com sinceridade. Você poderá atualizar depois os dados que '
        'mudam com o tempo.',
    ctaText: 'Começar',
  ),
  const Question(
    id: 'nickname',
    sectionTitle: 'Identidade básica',
    sectionDescription: 'Base pessoal',
    question: 'Como você quer ser chamado(a) no app?',
    type: QuestionType.text,
    helper: 'Pode ser um apelido. Você pode mudar depois no Perfil.',
  ),
  const Question(
    id: 'gender',
    sectionTitle: 'Identidade básica',
    sectionDescription: 'Base pessoal',
    question: 'Você é:',
    type: QuestionType.options,
    options: ['Homem', 'Mulher'],
  ),
  const Question(
    id: 'dob',
    sectionTitle: 'Identidade básica',
    sectionDescription: 'Base pessoal',
    question: 'Qual sua data de nascimento?',
    type: QuestionType.date,
    helper: 'Digite só os números. As barras serão colocadas automaticamente.',
  ),
  const Question(
    id: 'cpf',
    sectionTitle: 'Identidade básica',
    sectionDescription: 'Base pessoal',
    question: 'Quer adicionar CPF para liberar recursos no futuro?',
    type: QuestionType.text,
    optional: true,
    helper: 'Opcional. Digite só os 11 números do CPF ou toque em pular.',
  ),
];

/// Etapa 2: contexto de vida para personalizar o sistema de áreas
final List<Question> lifeQuestions = [
  const Question(
    id: 'living_with',
    sectionTitle: 'Casa e família',
    sectionDescription: 'Família e lar',
    question: 'Com quem você mora hoje?',
    type: QuestionType.options,
    options: [
      'Moro sozinho(a)',
      'Com pais',
      'Com parceiro(a)',
      'Com filhos',
      'Com parceiro(a) e filhos',
      'Com outros familiares',
      'Com amigos',
      'Outro',
    ],
  ),
  const Question(
    id: 'children_count',
    sectionTitle: 'Casa e família',
    sectionDescription: 'Família e lar',
    question: 'Você tem filhos?',
    type: QuestionType.options,
    options: ['Não', 'Sim, 1', 'Sim, 2', 'Sim, 3 ou mais'],
  ),
  const Question(
    id: 'family_relationship',
    sectionTitle: 'Casa e família',
    sectionDescription: 'Família e lar',
    question: 'Como está sua relação com sua família hoje?',
    type: QuestionType.options,
    options: ['Muito boa', 'Boa', 'Mais ou menos', 'Difícil', 'Muito difícil'],
  ),
  const Question(
    id: 'home_routine_load',
    sectionTitle: 'Casa e família',
    sectionDescription: 'Família e lar',
    question: 'A rotina da sua casa costuma ser:',
    type: QuestionType.options,
    options: ['Leve', 'Moderada', 'Corrida', 'Muito puxada', 'Instável'],
  ),
  const Question(
    id: 'study_work',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Hoje sua principal rotina é:',
    type: QuestionType.options,
    options: [
      'Trabalho',
      'Estudos',
      'Trabalho e estudos',
      'Cuido da casa',
      'Estou desempregado(a)',
      'Estou buscando me reorganizar',
      'Outro',
    ],
  ),
  const Question(
    id: 'occupation_type',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Qual é sua ocupação atual?',
    type: QuestionType.options,
    options: [
      'Empregado(a) CLT',
      'Autônomo(a)',
      'Empreendedor(a)',
      'Freelancer',
      'Estudante',
      'Do lar',
      'Desempregado(a)',
      'Outro',
    ],
  ),
  const Question(
    id: 'work_field',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Em que área você atua ou estuda hoje?',
    type: QuestionType.options,
    options: [
      'Saúde',
      'Educação',
      'Tecnologia',
      'Comércio',
      'Transporte',
      'Administração',
      'Serviços gerais',
      'Segurança',
      'Construção',
      'Comunicação',
      'Ainda não sei / variável',
      'Outro',
    ],
  ),
  const Question(
    id: 'work_schedule_format',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Sua rotina principal acontece em qual formato?',
    type: QuestionType.options,
    options: [
      'Horário fixo diurno',
      'Turnos',
      'Noturno',
      'Horário flexível',
      'Rotina muito variável',
      'Não se aplica',
    ],
  ),
  const Question(
    id: 'work_demand_type',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Seu trabalho ou estudo costuma exigir:',
    type: QuestionType.options,
    options: [
      'Mais esforço físico',
      'Mais esforço mental',
      'Equilíbrio entre os dois',
      'Pouca exigência no momento',
      'Não se aplica',
    ],
  ),
  const Question(
    id: 'work_satisfaction',
    sectionTitle: 'Trabalho e estudos',
    sectionDescription: 'Profissional e desenvolvimento',
    question: 'Como você se sente com sua vida profissional ou estudos hoje?',
    type: QuestionType.options,
    options: [
      'Muito satisfeito(a)',
      'Satisfeito(a)',
      'Neutro(a)',
      'Insatisfeito(a)',
      'Muito insatisfeito(a)',
    ],
  ),
  const Question(
    id: 'health_self_rating',
    sectionTitle: 'Saúde e corpo',
    sectionDescription: 'Corpo e saúde',
    question: 'Como você descreveria sua saúde hoje?',
    type: QuestionType.options,
    options: ['Muito boa', 'Boa', 'Média', 'Ruim', 'Muito ruim'],
  ),
  const Question(
    id: 'health_limitations',
    sectionTitle: 'Saúde e corpo',
    sectionDescription: 'Corpo e saúde',
    question:
        'Você tem alguma limitação física, condição de saúde ou cansaço '
        'frequente que afete sua rotina?',
    type: QuestionType.options,
    options: [
      'Não',
      'Sim, pouco',
      'Sim, moderadamente',
      'Sim, bastante',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'sleep_hours',
    sectionTitle: 'Saúde e corpo',
    sectionDescription: 'Corpo e saúde',
    question: 'Quantas horas você dorme em média por noite?',
    type: QuestionType.options,
    helper:
        'Depois isso poderá ser complementado por dados automáticos, como de smartwatch.',
    options: ['Menos de 5h', '5–6h', '6–7h', '7–8h', '8h+', 'Varia muito'],
  ),
  const Question(
    id: 'exercise_frequency',
    sectionTitle: 'Saúde e corpo',
    sectionDescription: 'Corpo e saúde',
    question: 'Com que frequência você pratica atividade física hoje?',
    type: QuestionType.options,
    options: [
      'Nunca',
      '1x por semana',
      '2–3x por semana',
      '4–5x por semana',
      'Quase todo dia',
      'Meu dia já é muito físico',
    ],
  ),
  const Question(
    id: 'last_checkup',
    sectionTitle: 'Saúde e corpo',
    sectionDescription: 'Corpo e saúde',
    question: 'Quando foi seu último check-up ou exame geral?',
    type: QuestionType.date,
    optional: true,
    helper:
        'Opcional. Digite só os números. As barras serão colocadas automaticamente.',
  ),
  const Question(
    id: 'stress_level',
    sectionTitle: 'Mente e emocional',
    sectionDescription: 'Mental e emocional',
    question: 'Como você descreveria seu nível de estresse atual?',
    type: QuestionType.options,
    options: ['Muito baixo', 'Baixo', 'Médio', 'Alto', 'Muito alto'],
  ),
  const Question(
    id: 'emotional_state',
    sectionTitle: 'Mente e emocional',
    sectionDescription: 'Mental e emocional',
    question: 'Como está seu emocional na maior parte dos dias?',
    type: QuestionType.options,
    options: [
      'Muito bem',
      'Bem',
      'Oscilando',
      'Mal',
      'Muito mal',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'rest_capacity',
    sectionTitle: 'Mente e emocional',
    sectionDescription: 'Mental e emocional',
    question: 'Você sente que tem tempo real para descansar ou se recuperar?',
    type: QuestionType.options,
    options: ['Sim, com frequência', 'Às vezes', 'Quase nunca', 'Nunca'],
  ),
  const Question(
    id: 'mental_load',
    sectionTitle: 'Mente e emocional',
    sectionDescription: 'Mental e emocional',
    question: 'Sua rotina atual te deixa mentalmente:',
    type: QuestionType.options,
    options: [
      'Leve',
      'Equilibrado(a)',
      'Cansado(a)',
      'Sobrecarregado(a)',
      'Esgotado(a)',
    ],
  ),
  const Question(
    id: 'life_demands_capacity',
    sectionTitle: 'Mente e emocional',
    sectionDescription: 'Mental e emocional',
    question: 'Você sente que consegue dar conta do que a vida pede hoje?',
    type: QuestionType.options,
    options: [
      'Sim, com folga',
      'Sim, razoavelmente',
      'Mais ou menos',
      'Quase não',
      'Não',
    ],
  ),
  const Question(
    id: 'financial_situation',
    sectionTitle: 'Finanças e estabilidade',
    sectionDescription: 'Finanças',
    question: 'Como você vê sua situação financeira hoje?',
    type: QuestionType.options,
    options: [
      'Muito organizada',
      'Organizada',
      'Mais ou menos',
      'Desorganizada',
      'Muito difícil',
    ],
  ),
  const Question(
    id: 'income_stability',
    sectionTitle: 'Finanças e estabilidade',
    sectionDescription: 'Finanças',
    question: 'Sua renda hoje é:',
    type: QuestionType.options,
    options: [
      'Estável',
      'Um pouco variável',
      'Muito variável',
      'Não tenho renda própria',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'financial_main_difficulty',
    sectionTitle: 'Finanças e estabilidade',
    sectionDescription: 'Finanças',
    question: 'Hoje você sente mais dificuldade em:',
    type: QuestionType.options,
    options: [
      'Ganhar dinheiro',
      'Controlar gastos',
      'Quitar dívidas',
      'Guardar dinheiro',
      'Organizar tudo',
      'Não tenho grande dificuldade agora',
    ],
  ),
  const Question(
    id: 'expense_tracking',
    sectionTitle: 'Finanças e estabilidade',
    sectionDescription: 'Finanças',
    question: 'Você costuma acompanhar seus gastos?',
    type: QuestionType.options,
    options: [
      'Sim, tudo',
      'Sim, a maior parte',
      'Só às vezes',
      'Quase nunca',
      'Nunca',
    ],
  ),
  const Question(
    id: 'dependents_financial',
    sectionTitle: 'Finanças e estabilidade',
    sectionDescription: 'Finanças',
    question: 'Hoje você tem alguém que depende financeiramente de você?',
    type: QuestionType.options,
    options: [
      'Não',
      'Sim, 1 pessoa',
      'Sim, 2 pessoas',
      'Sim, 3 ou mais',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'social_life',
    sectionTitle: 'Relações e apoio',
    sectionDescription: 'Relações e conexões',
    question: 'Como está sua vida social hoje?',
    type: QuestionType.options,
    options: ['Muito boa', 'Boa', 'Média', 'Fraca', 'Muito fraca'],
  ),
  const Question(
    id: 'emotional_support',
    sectionTitle: 'Relações e apoio',
    sectionDescription: 'Relações e conexões',
    question: 'Você sente que tem apoio emocional quando precisa?',
    type: QuestionType.options,
    options: ['Sim, bastante', 'Sim, um pouco', 'Quase não', 'Não'],
  ),
  const Question(
    id: 'romantic_relationship',
    sectionTitle: 'Relações e apoio',
    sectionDescription: 'Relações e conexões',
    question: 'Seu relacionamento amoroso hoje é:',
    type: QuestionType.options,
    options: [
      'Não tenho',
      'Está bem',
      'Está mais ou menos',
      'Está difícil',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'friendship_connection',
    sectionTitle: 'Relações e apoio',
    sectionDescription: 'Relações e conexões',
    question: 'Como está sua conexão com amigos hoje?',
    type: QuestionType.options,
    options: ['Muito boa', 'Boa', 'Média', 'Fraca', 'Quase inexistente'],
  ),
  const Question(
    id: 'loneliness',
    sectionTitle: 'Relações e apoio',
    sectionDescription: 'Relações e conexões',
    question: 'Na maior parte do tempo, você se sente:',
    type: QuestionType.options,
    options: [
      'Bem acompanhado(a)',
      'Às vezes acompanhado(a)',
      'Mais sozinho(a) do que gostaria',
      'Muito sozinho(a)',
      'Prefiro não responder',
    ],
  ),
  const Question(
    id: 'personal_organization',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question: 'No seu dia a dia, como costuma estar sua organização pessoal?',
    type: QuestionType.options,
    options: ['Muito boa', 'Boa', 'Média', 'Ruim', 'Muito ruim'],
  ),
  const Question(
    id: 'home_organization',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question:
        'No seu dia a dia, como costuma estar a organização da sua casa ou ambiente?',
    type: QuestionType.options,
    options: [
      'Muito boa',
      'Boa',
      'Média',
      'Ruim',
      'Muito ruim',
      'Não se aplica',
    ],
  ),
  const Question(
    id: 'screen_time',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question: 'Quanto tempo de tela você tem por dia, em média?',
    type: QuestionType.options,
    helper:
        'Depois isso poderá ser comparado com os dados automáticos do celular.',
    options: ['Menos de 2h', '2–4h', '4–6h', '6–8h', '8h+'],
  ),
  const Question(
    id: 'phone_usage_purpose',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question:
        'O celular que você mais usa no dia a dia é usado principalmente para:',
    type: QuestionType.options,
    options: [
      'Uso pessoal',
      'Uso profissional',
      'Uso pessoal e profissional',
      'Uso para estudos',
      'Uso misto para tudo',
    ],
  ),
  const Question(
    id: 'consistency',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question:
        'Você sente que consegue manter constância nas coisas importantes?',
    type: QuestionType.options,
    options: [
      'Sim, muito',
      'Sim, razoavelmente',
      'Mais ou menos',
      'Pouco',
      'Não',
    ],
  ),
  const Question(
    id: 'routine_predictability',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question: 'No geral, sua rotina costuma ser:',
    type: QuestionType.options,
    options: [
      'Muito previsível',
      'Relativamente organizada',
      'Um pouco bagunçada',
      'Bem corrida',
      'Totalmente imprevisível',
    ],
  ),
  const Question(
    id: 'routine_main_weight',
    sectionTitle: 'Rotina, casa e organização',
    sectionDescription: 'Hábitos, constância e ambiente',
    question: 'Hoje, o que mais pesa na sua rotina?',
    type: QuestionType.options,
    options: [
      'Falta de tempo',
      'Cansaço',
      'Dinheiro',
      'Filhos/família',
      'Trabalho',
      'Saúde',
      'Emocional',
      'Falta de organização',
      'Outro',
    ],
  ),
  const Question(
    id: 'focus',
    sectionTitle: 'Prioridades e direção',
    sectionDescription: 'Objetivo e foco',
    question: 'Qual área da vida mais precisa de atenção hoje?',
    type: QuestionType.options,
    options: [
      'Corpo & saúde',
      'Mental & emocional',
      'Finanças',
      'Trabalho/estudos',
      'Família',
      'Relacionamentos',
      'Casa e organização',
      'Hábitos e constância',
    ],
  ),
  const Question(
    id: 'goal',
    sectionTitle: 'Prioridades e direção',
    sectionDescription: 'Objetivo e foco',
    question: 'Qual é sua prioridade principal neste momento?',
    type: QuestionType.options,
    options: [
      'Me organizar',
      'Reduzir estresse',
      'Melhorar saúde',
      'Melhorar finanças',
      'Evoluir no trabalho/estudos',
      'Cuidar melhor da família',
      'Voltar a ter constância',
      'Outro',
    ],
  ),
  const Question(
    id: 'app_help',
    sectionTitle: 'Prioridades e direção',
    sectionDescription: 'Objetivo e foco',
    question: 'O que você mais quer que o app te ajude a fazer?',
    type: QuestionType.options,
    options: [
      'Entender minha vida melhor',
      'Ter mais clareza',
      'Criar rotina',
      'Melhorar hábitos',
      'Organizar finanças',
      'Cuidar da saúde',
      'Sair do caos',
      'Outro',
    ],
  ),
  const Question(
    id: 'start_preference',
    sectionTitle: 'Prioridades e direção',
    sectionDescription: 'Objetivo e foco',
    question: 'Você prefere começar com foco em:',
    type: QuestionType.options,
    options: [
      'Pequenos passos',
      'Resultados rápidos',
      'Entender minha realidade primeiro',
      'Plano mais completo',
      'Tanto faz',
    ],
  ),
];
